# src/seedlayer/cli.py
from __future__ import annotations

import importlib.util
import types
from pathlib import Path

import typer

app = typer.Typer(help="SeedLayer CLI")

DEFAULT_CONFIG_NAME = "seedlayer_config.py"

CONFIG_TEMPLATE = """\
# SeedLayer configuration
# Generated by `seedlayer init`

TYPE_DEFAULTS = []

# Optional: module with data factories/fixtures
SEED_MODULE = "example.dataseed"

# Optional DB URL (ex: Postgres, SQLite). Leave None to let your code decide.
DATABASE_URL = None  # e.g., "sqlite:///seed.db"

# Seeding options (define anything your library expects)
OPTIONS = {
    "batch_size": 500,
    "echo": False,
}

# Example: execution order hints, if your lib supports it
SEED_ORDER = [
    # "users",
    # "projects",
]
"""


# -------------------------
# Utilities
# -------------------------
def _load_config_module(cfg_path: Path) -> types.ModuleType:
    if not cfg_path.exists():
        raise FileNotFoundError(f"Config not found: {cfg_path}")
    spec = importlib.util.spec_from_file_location("seedlayer_config", cfg_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load spec from {cfg_path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# -------------------------
# Innit Command
# -------------------------
init_dir_option = typer.Option(
    Path("."), "--dir", "-d", help="Directory to place the config file in."
)
init_force_option = typer.Option(False, "--force", "-f", help="Overwrite if exists.")
init_name_option = typer.Option(DEFAULT_CONFIG_NAME, "--name", "-n", help="Config filename.")


@app.command()
def init(
    dir: Path = init_dir_option,
    force: bool = init_force_option,
    name: str = init_name_option,
) -> None:
    """Create a starter Python config file from a template."""
    dir.mkdir(parents=True, exist_ok=True)
    cfg_path = dir / name
    if cfg_path.exists() and not force:
        typer.echo(f"Refusing to overwrite existing {cfg_path}. Use --force.")
        raise typer.Exit(code=1)

    cfg_path.write_text(CONFIG_TEMPLATE)
    typer.echo(f"Created {cfg_path}")


# -------------------------
# Update Command
# -------------------------
update_config_option = typer.Option(
    Path(DEFAULT_CONFIG_NAME),
    "--config",
    "-c",
    help="Path to seedlayer config file.",
)


@app.command()
def update(
    config: Path = update_config_option,
) -> None:
    """Append updates to your config without manual editing."""
    if not config.exists():
        typer.echo(f"Config not found: {config}")
        raise typer.Exit(code=1)


# -------------------------
# Seed Command
# -------------------------

seed_config_option = typer.Option(
    Path(DEFAULT_CONFIG_NAME), "--config", "-c", help="Path to config file."
)


@app.command()
def seed(
    config: Path = seed_config_option,
) -> None:
    """Run seeding using your config. Tries seed.run(config=cfg) if available."""
    try:
        cfg = _load_config_module(config)
    except Exception as e:
        typer.echo(f"Failed to load config: {e}")
        raise typer.Exit(code=1) from None

    if cfg:
        pass


if __name__ == "__main__":
    app()
