# SeedLayer configuration
# Generated by `seedlayer init`

from sqlalchemy import create_engine

from seedlayer.constants import TypeDefaults
from seedlayer.types import SeedingPlan

# Type Default override
TYPE_DEFAULTS: TypeDefaults = {}

# Faker configuration
FAKER_SEED: int | None = None
FAKER_LOCAL: str | None = None

# DB engine (see https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine)
ENGINE = create_engine("<your_db_connection_URL>")

# The size of db insert batches in number of rows
BATCH_SIZE: int | None = None

# Model configuration
# Import your generated model classes here and add  seeding configuration


# Seeding plan : define how many rows to create for each of your models
SEEDING_PLAN: SeedingPlan = {
    # Users: 500,
    # Products: 5000,
    # ...
}
